In [63]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

auto_mpg = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']

# Load dataset
df = pd.read_csv('D:/Materi Kuliah UNAIR/Semester 5/Pembelajaran Mesin (Praktikum) RK-A2/auto-mpg.data.csv',
                 sep = r'\s+', header = None, names = auto_mpg, na_values = '?', on_bad_lines='skip')

# Set pandas options to display all rows and columns
pd.set_option('display.max_rows', None)   # Menampilkan semua baris
pd.set_option('display.max_columns', None) # Menampilkan semua kolom

# # Print the DataFrame
# df

In [64]:
for col in df.columns[:-1]:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [65]:
print(df['horsepower'].isna().sum())

6


In [66]:
from sklearn.preprocessing import MinMaxScaler 

array = df.values 
 
# Select column to rescale 
horsepower = array[:,3].reshape(-1,1)
 
# Rescaling data 
scaler = MinMaxScaler(feature_range=(0, 1)) 
rescaledX = scaler.fit_transform(horsepower) 

rescaledX

array([[0.45652174],
       [0.64673913],
       [0.56521739],
       [0.56521739],
       [0.51086957],
       [0.82608696],
       [0.94565217],
       [0.91847826],
       [0.97282609],
       [0.7826087 ],
       [0.67391304],
       [0.61956522],
       [0.56521739],
       [0.97282609],
       [0.26630435],
       [0.26630435],
       [0.27717391],
       [0.21195652],
       [0.22826087],
       [0.        ],
       [0.22282609],
       [0.23913043],
       [0.26630435],
       [0.36413043],
       [0.23913043],
       [0.91847826],
       [0.83695652],
       [0.89130435],
       [0.79891304],
       [0.22826087],
       [0.23913043],
       [0.26630435],
       [       nan],
       [0.29347826],
       [0.32065217],
       [0.29347826],
       [0.22826087],
       [0.29347826],
       [0.64673913],
       [0.70108696],
       [0.58152174],
       [0.56521739],
       [0.72826087],
       [0.67391304],
       [0.70108696],
       [0.34782609],
       [0.14130435],
       [0.293

In [67]:
from sklearn.preprocessing import Binarizer

df = df.dropna(subset=['horsepower'])  
array = df.values

# Binarize the data  
binarizer = Binarizer(threshold=100.0)  
binaryX = binarizer.fit_transform(array[:, 3].reshape(-1, 1)) 

binaryX

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],

In [68]:
from sklearn.preprocessing import StandardScaler

# preparation of dataframe using the data at given link and defined columns list 
array = df.values 
 
# Select column to rescale 
horsepower = array[:,3].reshape(-1,1)
 
# Standardize data 
scaler = StandardScaler().fit(horsepower) 
rescaledX = scaler.transform(horsepower) 

rescaledX

array([[ 0.66413273],
       [ 1.57459447],
       [ 1.18439658],
       [ 1.18439658],
       [ 0.92426466],
       [ 2.43302983],
       [ 3.00532006],
       [ 2.8752541 ],
       [ 3.13538603],
       [ 2.22492429],
       [ 1.70466044],
       [ 1.44452851],
       [ 1.18439658],
       [ 3.13538603],
       [-0.24632901],
       [-0.24632901],
       [-0.19430262],
       [-0.50646093],
       [-0.42842136],
       [-1.52097544],
       [-0.45443455],
       [-0.37639497],
       [-0.24632901],
       [ 0.22190846],
       [-0.37639497],
       [ 2.8752541 ],
       [ 2.48505621],
       [ 2.74518814],
       [ 2.30296387],
       [-0.42842136],
       [-0.37639497],
       [-0.24632901],
       [-0.11626304],
       [ 0.01380292],
       [-0.11626304],
       [-0.42842136],
       [-0.11626304],
       [ 1.57459447],
       [ 1.8347264 ],
       [ 1.26243616],
       [ 1.18439658],
       [ 1.96479236],
       [ 1.70466044],
       [ 1.8347264 ],
       [ 0.14386888],
       [-0