In [248]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
# import tensorflow as tf
# import tensorflow.keras as keras
# from tensorflow.keras.layers import Dense, Input, Dropout
import matplotlib.pyplot as plt


headers = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv('D:/Materi Kuliah UNAIR/Semester 5/Pembelajaran Mesin (Praktikum) RK-A2/iris/iris.data',
                 header=None, names=headers)

# # Set pandas options to display all rows and columns
# pd.set_option('display.max_rows', None)   # Menampilkan semua baris
# pd.set_option('display.max_columns', None) # Menampilkan semua kolom

print(df)


     sepal_length  sepal_width  petal_length  petal_width            class
0             5.1          3.5           1.4          0.2      Iris-setosa
1             4.9          3.0           1.4          0.2      Iris-setosa
2             4.7          3.2           1.3          0.2      Iris-setosa
3             4.6          3.1           1.5          0.2      Iris-setosa
4             5.0          3.6           1.4          0.2      Iris-setosa
5             5.4          3.9           1.7          0.4      Iris-setosa
6             4.6          3.4           1.4          0.3      Iris-setosa
7             5.0          3.4           1.5          0.2      Iris-setosa
8             4.4          2.9           1.4          0.2      Iris-setosa
9             4.9          3.1           1.5          0.1      Iris-setosa
10            5.4          3.7           1.5          0.2      Iris-setosa
11            4.8          3.4           1.6          0.2      Iris-setosa
12            4.8        

### Setting 'Class' menjadi Target

In [249]:
X = df.drop('class', axis=1)
y = df['class']

print(y)

0          Iris-setosa
1          Iris-setosa
2          Iris-setosa
3          Iris-setosa
4          Iris-setosa
5          Iris-setosa
6          Iris-setosa
7          Iris-setosa
8          Iris-setosa
9          Iris-setosa
10         Iris-setosa
11         Iris-setosa
12         Iris-setosa
13         Iris-setosa
14         Iris-setosa
15         Iris-setosa
16         Iris-setosa
17         Iris-setosa
18         Iris-setosa
19         Iris-setosa
20         Iris-setosa
21         Iris-setosa
22         Iris-setosa
23         Iris-setosa
24         Iris-setosa
25         Iris-setosa
26         Iris-setosa
27         Iris-setosa
28         Iris-setosa
29         Iris-setosa
30         Iris-setosa
31         Iris-setosa
32         Iris-setosa
33         Iris-setosa
34         Iris-setosa
35         Iris-setosa
36         Iris-setosa
37         Iris-setosa
38         Iris-setosa
39         Iris-setosa
40         Iris-setosa
41         Iris-setosa
42         Iris-setosa
43         

In [250]:
from sklearn.preprocessing import LabelEncoder

# Convert the 'class' column to numerical labels
le = LabelEncoder()
y = le.fit_transform(y)

print(y)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Split untuk Training Data (70%), Test Data (30%)

In [251]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Training Decision Tree

In [252]:
# Decision tree using Gini criterion
clf_gini = DecisionTreeClassifier(criterion='gini', random_state=42)
clf_gini.fit(X_train, y_train)

# Decision tree using Entropy criterion
clf_entropy = DecisionTreeClassifier(criterion='entropy', random_state=42)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [253]:
def classifier_data(observation, arbol):
    question = list(arbol.keys())[0]
    if question.split()[1] == '<=':
        if observation[question.split()[0]] <= float(question.split()[2]):
            answer = arbol[question][0]
        else:
            answer = arbol[question][1]
    else:
        if observation[question.split()[0]] in (question.split()[2]):
            answer = arbol[question][0]
        else:
            answer = arbol[question][1]

    if not isinstance(answer, dict):
        return answer
    else:
        residual_tree = answer
        return classifier_data(observation, answer)


### Prediksi Menggunakan Decision Tree

In [254]:
# Model Decision Tree menggunakan Gini
clf_gini = DecisionTreeClassifier(criterion='gini', random_state=42)
clf_gini.fit(X_train, y_train)

# Model Decision Tree menggunakan Entropy
clf_entropy = DecisionTreeClassifier(criterion='entropy', random_state=42)
clf_entropy.fit(X_train, y_train)

# Prediksi menggunakan model Gini
y_pred_gini = clf_gini.predict(X_test)

# Prediksi menggunakan model Entropy
y_pred_entropy = clf_entropy.predict(X_test)

# Confusion matrix untuk model Gini
conf_matrix_gini = confusion_matrix(y_test, y_pred_gini)

# Confusion matrix untuk model Entropy
conf_matrix_entropy = confusion_matrix(y_test, y_pred_entropy)

print("Confusion Matrix Gini:\n", conf_matrix_gini)
print("\nConfusion Matrix Entropy:\n", conf_matrix_entropy)

Confusion Matrix Gini:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Confusion Matrix Entropy:
 [[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]


### Menghitung Confusion Matrix dan Metrik Evaluasi

In [255]:
# Fungsi untuk menghitung metrik evaluasi
def calculate_metrics(conf_matrix, y_true, y_pred):
    # Akurasi
    accuracy = accuracy_score(y_true, y_pred)
    
    # Presisi (macro averaged untuk beberapa kelas)
    precision = precision_score(y_true, y_pred, average='macro')
    
    # Sensitivitas/Recall (macro averaged untuk beberapa kelas)
    sensitivity = recall_score(y_true, y_pred, average='macro')
    
    # Menghitung spesifisitas berdasarkan confusion matrix
    specificity = []
    for i in range(conf_matrix.shape[0]):
        tn = conf_matrix.sum() - (conf_matrix[i, :].sum() + conf_matrix[:, i].sum() - conf_matrix[i, i])
        fp = conf_matrix[:, i].sum() - conf_matrix[i, i]
        specificity.append(tn / (tn + fp))
    
    specificity = sum(specificity) / len(specificity)
    
    return accuracy, precision, sensitivity, specificity


### Hasil Evaluasi

In [256]:
# Menghitung metrik untuk model Gini
metrics_gini = calculate_metrics(conf_matrix_gini, y_test, y_pred_gini)

# Menghitung metrik untuk model Entropy
metrics_entropy = calculate_metrics(conf_matrix_entropy, y_test, y_pred_entropy)

print("Metrics for Gini Decision Tree:")
print(f"Accuracy: {metrics_gini[0]*100:.2f}%")
print(f"Precision: {metrics_gini[1]*100:.2f}%")
print(f"Sensitivity (Recall): {metrics_gini[2]*100:.2f}%")
print(f"Specificity: {metrics_gini[3]*100:.2f}%")

print("\nMetrics for Entropy Decision Tree:")
print(f"Accuracy: {metrics_entropy[0]*100:.2f}%")
print(f"Precision: {metrics_entropy[1]*100:.2f}%")
print(f"Sensitivity (Recall): {metrics_entropy[2]*100:.2f}%")
print(f"Specificity: {metrics_entropy[3]*100:.2f}%")

Metrics for Gini Decision Tree:
Accuracy: 100.00%
Precision: 100.00%
Sensitivity (Recall): 100.00%
Specificity: 100.00%

Metrics for Entropy Decision Tree:
Accuracy: 97.78%
Precision: 97.62%
Sensitivity (Recall): 97.44%
Specificity: 98.96%
